repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: pdm run black src/
        language: system
        types: [python]
      - id: system
        name: ruff check
        entry: pdm run ruff check src/ --fix
        language: system
        types: [python]
