repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: pdm run black src/
        language: system
        types: [python]
      - id: system
        name: isort
        entry: pdm run isort src/
        language: system
        types: [python]
      - id: system
        name: flake9
        entry: pdm run flake8 src/
        language: system
        types: [python]
