---
version: "3.8"
services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      TOKEN: "${TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      TEST_SERVER: "${TEST_SERVER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    deploy:
      restart_policy:
        condition: "unless-stopped"
    depends_on:
      - database
  database:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
